# syntax=docker/dockerfile:1
FROM ubuntu:latest
RUN apt-get update && apt-get install -y && apt-get update
RUN apt-get install -y cron
RUN apt-get install -y python3-pip

ARG AUTH
ENV AUTH=$AUTH
ENV TZ=Europe/Paris

RUN mkdir API
ADD . /API
WORKDIR /API
RUN pip3 install -r requirements.txt

COPY . .

RUN service cron start
CMD cron &  python3 ./run.py